### ISSUE TITLE
Can't add tags

### ISSUE THREAD

**Issue by adityabansod** [ActiveCampaign/activecampaign-api-nodejs#10]
This code fires a `Invalid API method` error:

```
		var eventdata = {
		    tag: 'somesampletag',
		    email: 'example@example.com'
		};

		ac.api('contact/tag/add', eventdata).then(function(result) {
		    console.log('success', result);
		}, function(result) {
			console.log('failure', redirect);
		});		
```

the contact has been created earlier by calling `ac.api('contact/add')`.

**Comment by mthommes** [comment]
Hi, thanks for pointing this out. This should be fixed now (Github and NPM have been updated).

Here is a working example (I included multiple tags just for demonstration):

	var eventdata = {
		tags: 'somesampletag,somesampletag2',
		email: 'example@example.com'
	};

	ac.api('contact/tag/add', eventdata);

Let us know of any problems or questions! :+1:
