### ISSUE TITLE
Cannot retrieve contacts by listid

### ISSUE THREAD

**Issue by landland** [ActiveCampaign/activecampaign-api-nodejs#16]
Hello, I can't seem to retrieve contacts by listid. Here's my code

```
var contacts_get = ac.api("contact/list?listid=1", {});
        contacts_get.then(function(result) {
            // successful request
            console.log("result is ", result);
        }, function(result) {
            // request error
        });
```

However, if I change the request `contact/list?ids=all` I get all contacts. I've also tried `contact/list?ids=all&listid=1` but that returns all contacts, even those not part of the listid. Is this a bug or am I missing something? Thanks.

**Comment by ac-pevans** [comment]
You should be able to use the filter parameter to pass in a list id. Check out the [example script](http://www.activecampaign.com/api/example.php?call=contact_list) for contact_list, which mentions all the possible filter params you can use.

**Comment by landland** [comment]
That's what I think I did. I used the filter `listid=1` but it didn't work. Am I entering the filter incorrectly?

**Comment by landland** [comment]
I see. I had to use `filters[listid]=1`. I didn't see that in the node docs. Thank you.

**Comment by ac-pevans** [comment]
You're welcome! Glad it's working for you now.
