### ISSUE TITLE
Is this fully functional ?

### ISSUE THREAD

**Issue by Vivek2s** [ActiveCampaign/activecampaign-api-nodejs#32]
I want to get all list & also want to view the contact.So I'm using this code:
ac.api("list/view",{}); 
output : "result_code": 0,
    "result_message": "Failed: Nothing is returned",
    "result_output": "json",
    "success": 0,
    "error": "Failed: Nothing is returned"

Could you please tell me how can I make the request for getting all List & add contact in the List by using this wrapper

**Comment by mthommes** [comment]
Hi, please try the following:

```var ActiveCampaign = require("activecampaign");

var ac = new ActiveCampaign("API URL", "API KEY");
ac.debug = true;

// Get lists
var lists = ac.api("list/list?ids=all", {}).then(function(result) {
	console.log(result);
});

// Add contact
var post_test = ac.api("contact/add", {
	email: 'nodetest@test.com'
}).then(function(result) {
	// successful request
	console.log(result);
}, function(result) {
	// request error
});
