### ISSUE TITLE
Problem with connector url

### ISSUE THREAD

**Issue by plarrea** [ActiveCampaign/activecampaign-api-nodejs#35]
I have a problem with how the url is built, after I log an event with api('tracking/log'), the connector url changes to "https://trackcmp.net/event", making all the other api calls imposible to reach after that.

I keep getting this error with all calls as if i was trying to log an event:
`{"success":0,"message":"An account ID must be provided."}`

Is there a way to reset the connector to the original url? Am I missing something?

Cheers

**Comment by mthommes** [comment]
Hello! We have a fix on the way for this issue (#36).

**Comment by mthommes** [comment]
[NPM](https://www.npmjs.com/package/activecampaign) has been updated to version 1.2.4 which should fix this issue. Let us know if you still notice anything not working! 👍

**Comment by DavidLopezS** [comment]
Hi, I'm trying to send a request for track event endpoint "https://trackcmp.net/event" and I'm having the same issue. I'm getting the `actid` and `key` from Event Tracking page and the event name is correct. Am I missing something?

Thank you in advance!

**Comment by cameronhayglass** [comment]
@DavidLopezS I don't know if this is intentional but I had the same problem, and solved it by passing as URL params instead of in the body. Not claiming that's good/correct, but it worked for me.
