### ISSUE TITLE
Cannot find module when using in meteor.js

### ISSUE THREAD

**Issue by joesamcoke** [ActiveCampaign/activecampaign-api-nodejs#38]
I have installed and tested the packed in meteor.js locally and is working fine.

After deploying to a staging server I get the following error..

/bundle/programs/server/node_modules/fibers/future.js:280
throw(ex);
^
Error: Cannot find module '/node_modules/activeCampaign/lib/Connector'
at require (packages/modules-runtime.js:123:19)
at meteorInstall.node_modules.activeCampaign.lib.ActiveCampaign.js (packages/modules.js:985:17)

**Comment by ac-pevans** [comment]
I'm sorry, but this doesn't seem to be an issue for us. It looks rather like the package wasn't installed on your staging server for some reason, which I am afraid I can't help with.

**Comment by alexnault** [comment]
With Meteor, you probably ended bundling `activecampaign` for the client browser. We too had this error when using this package on the client in a Meteor app.

The solution was to import `activecampaign` on the server only. This lib will not work on a browser anyway afaik.
